# Generated by Django 4.2.1 on 2023-05-26 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='detsale',
            name='fpago',
            field=models.CharField(default='Efectivo', max_length=100),
        ),
    ]
