# Generated by Django 4.2.1 on 2023-06-02 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='desc',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=9),
        ),
    ]
