# Generated by Django 4.2.1 on 2023-06-02 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0002_detsale_fpago'),
        ('sale', '0002_sale_desc'),
    ]

    operations = [
    ]
