# Generated by Django 4.2.1 on 2023-05-21 03:18

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaent', models.DateField(default=datetime.datetime.now, verbose_name='Fecha de Entrada del Producto')),
                ('factura', models.CharField(default='Ninguna', max_length=15, verbose_name='Factura de Entrada del Producto')),
                ('codigo', models.CharField(max_length=15, unique=True, verbose_name='Codigo del Producto')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='Nombre')),
                ('image', models.ImageField(blank=True, null=True, upload_to='product/%Y/%m/%d', verbose_name='Imagen')),
                ('pvp', models.DecimalField(decimal_places=2, default=0.0, max_digits=9, verbose_name='Precio de venta')),
                ('pcp', models.DecimalField(decimal_places=2, default=0.0, max_digits=9, verbose_name='Precio de costo')),
                ('um', models.CharField(choices=[('u', 'Unidad'), ('Lbrs', 'Libras'), ('Kgs', 'Kilogramos'), ('L', 'Litros'), ('ml', 'Mililitros')], default='U', max_length=150, verbose_name='Unidad de Medidas')),
                ('cant', models.IntegerField(default=1, verbose_name='Cantidad Inicial')),
                ('fechacad', models.DateField(default=datetime.datetime.now, verbose_name='Fecha de Vencimiento del Producto')),
                ('stock', models.IntegerField(default=1, verbose_name='Stock Minimo')),
                ('cat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='category.category', verbose_name='Categoría')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'ordering': ['id'],
            },
        ),
    ]
