# Generated by Django 4.2.1 on 2023-05-22 04:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_alter_product_cat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='cant',
        ),
    ]
