# Generated by Django 4.2.1 on 2023-05-24 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_remove_product_cant'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='cant',
            field=models.IntegerField(default=0, verbose_name='Cantidad Inicial'),
        ),
    ]
