# Generated by Django 4.2.1 on 2023-06-02 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_remove_product_cant_product_stock_min_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='prov',
            field=models.CharField(default='Predeterminado', max_length=15, unique=True, verbose_name='Proveedor del Producto'),
        ),
    ]
